version: "3.8"

services:
  postgres:
    image: postgres:13
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
  hasura:
    image: hasura/graphql-engine:v2.0.7
    environment:
      HASURA_GRAPHQL_DATABASE_URL: postgres://postgres:postgres@postgres:5432/postgres
      HASURA_GRAPHQL_ENABLE_CONSOLE: "true"
      EMAIL_REMINDER_TRIGGER_URL: whatever
    ports:
      - "8080:8080"
    depends_on:
      - postgres
  server:
    build: server
    ports:
      - 5000:4000
